/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path')
const fs = require('fs')
const express = require('express')
const compression = require('compression')
const morgan = require('morgan')

// Initialize Express app
const app = express()

// Middleware
app.use(compression())
app.use(morgan('combined'))

// Serve static assets from the PWA Kit build directory
const buildDir = path.join(__dirname, 'build')
app.use(express.static(buildDir, { maxAge: '1y', index: false }))

// Dynamically check all possible build output filenames generated by PWA Kit
const possiblePaths = [
    path.join(buildDir, 'server.js'),
    path.join(buildDir, 'ssr.js'),
    path.join(buildDir, 'main.js'),
    path.join(buildDir, 'index.js'),
    path.join(buildDir, 'bundle', 'server.js'),
    path.join(buildDir, 'bundle', 'ssr.js')
]

let serverHandler = null
for (const p of possiblePaths) {
    if (fs.existsSync(p)) {
        try {
            const mod = require(p)
            serverHandler = mod.handler || mod.default || mod
            console.log(`✅ Successfully loaded SSR handler from: ${p}`)
            break
        } catch (e) {
            console.error(`Failed to require ${p}:`, e)
        }
    }
}

// Route requests through the SSR handler if found
if (serverHandler) {
    app.all('*', (req, res) => {
        return serverHandler(req, res)
    })
} else {
    console.warn('⚠️ Compiled server handler not found in build/. Serving fallback message.')
    app.get('*', (req, res) => {
        res.status(503).send('Storefront build files are compiling. Please refresh in a moment.')
    })
}

// Bind to Railway's assigned port (or fallback to 3000 locally)
const PORT = process.env.PORT || 3000
app.listen(PORT, '0.0.0.0', () => {
    console.log(`🚀 Asda Storefront server is running and listening on port ${PORT}`)
})